var ALIASES = {};
ALIASES["actix_files"] = {};
ALIASES["actix_http"] = {};
ALIASES["actix_http_test"] = {};
ALIASES["actix_multipart"] = {};
ALIASES["actix_web"] = {};
ALIASES["actix_web_actors"] = {};
ALIASES["actix_web_codegen"] = {};
ALIASES["awc"] = {};
